/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type HeroCarouselSection = {
  _type: "heroCarouselSection";
  slides?: Array<{
    _key: string;
  } & HeroSlide>;
};

export type EventsCarouselSection = {
  _type: "eventsCarouselSection";
  heading?: string;
  limit?: number;
  backgroundColor?: SimplerColor;
  showCalendar?: boolean;
};

export type PressCarouselSection = {
  _type: "pressCarouselSection";
  heading?: string;
  limit?: number;
  backgroundColor?: SimplerColor;
};

export type BlogPostsCarouselSection = {
  _type: "blogPostsCarouselSection";
  heading?: string;
  limit?: number;
  backgroundColor?: SimplerColor;
};

export type ThreeColumnSection = {
  _type: "threeColumnSection";
  description: string;
  backgroundColor?: SimplerColor;
  ratio?: "1-1-1" | "2-1-1" | "1-2-1" | "1-1-2";
  column1?: RichText;
  column2?: RichText;
  column3?: RichText;
};

export type TwoColumnSection = {
  _type: "twoColumnSection";
  description: string;
  backgroundColor?: SimplerColor;
  ratio?: "1-1" | "3-2" | "2-3" | "2-1" | "1-2";
  leftColumn?: RichText;
  rightColumn?: RichText;
};

export type FullWidthSection = {
  _type: "fullWidthSection";
  description: string;
  content?: RichText;
};

export type BannerSection = {
  _type: "bannerSection";
  backgroundColor?: SimplerColor;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: RichText;
};

export type HeroSlide = {
  _type: "heroSlide";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heading?: string;
  text?: string;
  buttonText?: string;
  buttonLink?: string;
  buttonColor?: SimplerColor;
  buttonTextColor?: SimplerColor;
  overlayColor?: SimplerColor;
  overlayOpacity?: number;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<unknown // Unable to locate the referenced type "link" in schema
  | {
    _key: string;
  } & Color | unknown // Unable to locate the referenced type "backgroundColor" in schema
  >;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & RichTextImage | {
  _key: string;
} & RichTextButton | {
  _key: string;
} & Table>;

export type RichTextButton = {
  _type: "richTextButton";
  text: string;
  link: string;
  color?: SimplerColor;
  textColor?: SimplerColor;
  style?: "solid" | "transparent";
  size?: "sm" | "default" | "lg";
};

export type RichTextImage = {
  _type: "richTextImage";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type BackgroundColorAnnotation = {
  _type: "backgroundColorAnnotation";
  value?: SimplerColor;
};

export type ColorAnnotation = {
  _type: "colorAnnotation";
  value?: SimplerColor;
};

export type LinkAnnotation = {
  _type: "linkAnnotation";
  href?: string;
  blank?: boolean;
};

export type PressArticle = {
  _id: string;
  _type: "pressArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  publication?: string;
  excerpt?: string;
  url?: string;
  publishedAt?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<string>;
  backgroundColor?: SimplerColor;
};

export type SimplerColor = {
  _type: "simplerColor";
  label?: string;
  value?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt?: string;
  content?: Markdown;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
  category?: "News" | "Action" | "Victory" | "Analysis";
  tags?: Array<string>;
  backgroundColor?: SimplerColor;
};

export type Markdown = string;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
  date?: string;
  location?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  actionNetworkUrl?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  backgroundColor?: SimplerColor;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  sections?: Array<{
    _key: string;
  } & HeroCarouselSection | {
    _key: string;
  } & BannerSection | {
    _key: string;
  } & FullWidthSection | {
    _key: string;
  } & TwoColumnSection | {
    _key: string;
  } & ThreeColumnSection | {
    _key: string;
  } & BlogPostsCarouselSection | {
    _key: string;
  } & PressCarouselSection | {
    _key: string;
  } & EventsCarouselSection>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  siteName?: string;
};

export type Table = {
  _type: "table";
  rows?: Array<{
    _key: string;
  } & TableRow>;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type HighlightColor = {
  _type: "highlightColor";
  label?: string;
  value?: string;
};

export type TextColor = {
  _type: "textColor";
  label?: string;
  value?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = HeroCarouselSection | EventsCarouselSection | PressCarouselSection | BlogPostsCarouselSection | ThreeColumnSection | TwoColumnSection | FullWidthSection | BannerSection | HeroSlide | RichText | RichTextButton | RichTextImage | BackgroundColorAnnotation | ColorAnnotation | LinkAnnotation | PressArticle | SimplerColor | SanityImageCrop | SanityImageHotspot | BlogPost | Markdown | Slug | Event | Page | SiteSettings | Table | TableRow | MediaTag | HighlightColor | TextColor | Color | RgbaColor | HsvaColor | HslaColor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
