/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    events: Event;
    campaigns: Campaign;
    'press-articles': PressArticle;
    'team-members': TeamMember;
    books: Book;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    'press-articles': PressArticlesSelect<false> | PressArticlesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * All pages on the site. Build pages by adding sections below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  sections?:
    | (
        | {
            /**
             * Helps identify this section when collapsed in the admin
             */
            label?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            backgroundColor?:
              | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
              | null;
            backgroundImage?: (string | null) | Media;
            /**
             * Adds a dark semi-transparent overlay to improve text readability
             */
            darkScrim?: boolean | null;
            padding?: ('none' | 'small' | 'standard' | 'large') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerSection';
          }
        | {
            /**
             * Helps identify this section when collapsed in the admin
             */
            label?: string | null;
            slides?:
              | {
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  backgroundColor?:
                    | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
                    | null;
                  backgroundImage?: (string | null) | Media;
                  /**
                   * Adds a dark semi-transparent overlay to improve text readability
                   */
                  darkScrim?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroCarouselSection';
          }
        | {
            /**
             * Helps identify this section when collapsed in the admin
             */
            label?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            backgroundColor?:
              | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
              | null;
            backgroundImage?: (string | null) | Media;
            /**
             * Adds a dark semi-transparent overlay to improve text readability
             */
            darkScrim?: boolean | null;
            padding?: ('none' | 'small' | 'standard' | 'large') | null;
            /**
             * Drag and resize images in the preview box, then configure details below.
             */
            floatingItems?:
              | {
                  image: string | Media;
                  position: {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                  };
                  mobilePosition: {
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullWidthSection';
          }
        | {
            /**
             * Helps identify this section when collapsed in the admin
             */
            label?: string | null;
            wrapOnMobile?: boolean | null;
            ratio?: ('1-1' | '3-2' | '2-3') | null;
            leftColumn?: {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              backgroundColor?:
                | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
                | null;
              backgroundImage?: (string | null) | Media;
              /**
               * Adds a dark semi-transparent overlay to improve text readability
               */
              darkScrim?: boolean | null;
            };
            rightColumn?: {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              backgroundColor?:
                | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
                | null;
              backgroundImage?: (string | null) | Media;
              /**
               * Adds a dark semi-transparent overlay to improve text readability
               */
              darkScrim?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnSection';
          }
        | {
            /**
             * Helps identify this section when collapsed in the admin
             */
            label?: string | null;
            wrapOnMobile?: boolean | null;
            column1?: {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              backgroundColor?:
                | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
                | null;
              backgroundImage?: (string | null) | Media;
              /**
               * Adds a dark semi-transparent overlay to improve text readability
               */
              darkScrim?: boolean | null;
            };
            column2?: {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              backgroundColor?:
                | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
                | null;
              backgroundImage?: (string | null) | Media;
              /**
               * Adds a dark semi-transparent overlay to improve text readability
               */
              darkScrim?: boolean | null;
            };
            column3?: {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              backgroundColor?:
                | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
                | null;
              backgroundImage?: (string | null) | Media;
              /**
               * Adds a dark semi-transparent overlay to improve text readability
               */
              darkScrim?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'threeColumnSection';
          }
        | {
            /**
             * Helps identify this section when collapsed in the admin
             */
            label?: string | null;
            title?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            showAddress?: boolean | null;
            showEmail?: boolean | null;
            showSocialIcons?: boolean | null;
            showForm?: boolean | null;
            backgroundColor?:
              | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
              | null;
            backgroundImage?: (string | null) | Media;
            /**
             * Adds a dark semi-transparent overlay to improve text readability
             */
            darkScrim?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSection';
          }
        | {
            /**
             * Helps identify this section when collapsed in the admin
             */
            label?: string | null;
            alignment?: ('left' | 'center' | 'right') | null;
            verticalAlignment?: ('top' | 'center' | 'bottom') | null;
            padding?: ('none' | 'sm' | 'md' | 'lg') | null;
            gap?: ('none' | 'sm' | 'md' | 'lg') | null;
            wrapOnMobile?: boolean | null;
            items?:
              | {
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  backgroundColor?:
                    | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
                    | null;
                  backgroundImage?: (string | null) | Media;
                  /**
                   * Adds a dark semi-transparent overlay to improve text readability
                   */
                  darkScrim?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentGridSection';
          }
        | {
            /**
             * Helps identify this section when collapsed in the admin
             */
            label?: string | null;
            title?: string | null;
            subtitle?: string | null;
            /**
             * Which collection to pull items from
             */
            dataSource:
              | 'events'
              | 'blog-posts'
              | 'press-articles'
              | 'books'
              | 'team-members'
              | 'campaigns'
              | 'products';
            layout?: ('grid' | 'list' | 'carousel' | 'featured') | null;
            columns?: ('2' | '3' | '4') | null;
            limit?: number | null;
            sortField?: ('createdAt_desc' | 'createdAt_asc' | 'title_asc' | 'order_asc' | 'startDate_asc') | null;
            filterFeatured?: boolean | null;
            upcomingOnly?: boolean | null;
            viewAllLabel?: string | null;
            viewAllLinkType?: ('page' | 'url') | null;
            viewAllPage?: (string | null) | Page;
            viewAllUrl?: string | null;
            emptyMessage?: string | null;
            /**
             * Manually select items to always appear at the top, regardless of sort order
             */
            pinnedItems?:
              | {
                  item?:
                    | ({
                        relationTo: 'events';
                        value: string | Event;
                      } | null)
                    | ({
                        relationTo: 'blog-posts';
                        value: string | BlogPost;
                      } | null)
                    | ({
                        relationTo: 'press-articles';
                        value: string | PressArticle;
                      } | null)
                    | ({
                        relationTo: 'books';
                        value: string | Book;
                      } | null)
                    | ({
                        relationTo: 'campaigns';
                        value: string | Campaign;
                      } | null)
                    | ({
                        relationTo: 'products';
                        value: string | Product;
                      } | null)
                    | ({
                        relationTo: 'team-members';
                        value: string | TeamMember;
                      } | null);
                  id?: string | null;
                }[]
              | null;
            backgroundColor?:
              | ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300')
              | null;
            backgroundImage?: (string | null) | Media;
            /**
             * Adds a dark semi-transparent overlay to improve text readability
             */
            darkScrim?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'collectionListSection';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Community events, rallies, fundraisers, and meetings. Some fields are synced from Action Network and cannot be edited.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Synced from Action Network — do not edit manually
   */
  actionNetworkId?: string | null;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate: string;
  endDate?: string | null;
  location?: {
    venue?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  /**
   * RSVP link from Action Network — do not edit manually
   */
  browserUrl?: string | null;
  /**
   * For manually-created events not from Action Network
   */
  registrationUrl?: string | null;
  /**
   * Synced from Action Network
   */
  capacity?: number | null;
  /**
   * Synced from Action Network
   */
  totalAccepted?: number | null;
  slug?: string | null;
  status?: ('draft' | 'published' | 'hidden' | 'cancelled') | null;
  featured?: boolean | null;
  featuredImage?: (string | null) | Media;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eventType?:
    | ('town-hall' | 'rally' | 'fundraiser' | 'social' | 'workshop' | 'canvassing' | 'community-meeting' | 'press')
    | null;
  ticketed?: boolean | null;
  ticketUrl?: string | null;
  isFree?: boolean | null;
  price?: string | null;
  image?: (string | null) | Media;
  order?: number | null;
  speakers?:
    | {
        name: string;
        title?: string | null;
        bio?: string | null;
        photo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  sponsors?:
    | {
        name: string;
        logo?: (string | null) | Media;
        url?: string | null;
        tier?: ('platinum' | 'gold' | 'silver' | 'bronze') | null;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoKeywords?: string | null;
  backgroundColor?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'base-100' | 'base-200' | 'base-300') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  /**
   * Shown as hero on the post page and as thumbnail in lists
   */
  image?: (string | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  /**
   * Select a team member as author
   */
  author?: (string | null) | TeamMember;
  /**
   * Use if author is not a team member
   */
  authorName?: string | null;
  category?: ('News' | 'campaign-update' | 'Action' | 'Victory' | 'Analysis' | 'press-release' | 'community') | null;
  featured?: boolean | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select related blog posts to display
   */
  relatedPosts?: (string | BlogPost)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * OCAB staff, board members, and volunteer leaders
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string;
  name: string;
  role?: string | null;
  pronouns?: string | null;
  type?: ('staff' | 'board' | 'volunteer') | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (string | null) | Media;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * News coverage of OCAB from external publications
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-articles".
 */
export interface PressArticle {
  id: string;
  title: string;
  publication?: string | null;
  type?: ('news' | 'op-ed' | 'interview' | 'photo-essay') | null;
  excerpt?: string | null;
  url: string;
  image?: (string | null) | Media;
  /**
   * Featured articles appear in the press section on the homepage
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  publishedAt: string;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Books on the OCAB bookshelf
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: string;
  title: string;
  author?: string | null;
  year?: number | null;
  isbn?: string | null;
  description?: string | null;
  cover?: (string | null) | Media;
  url?: string | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Campaigns, research, reports, and other OCAB work
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: string;
  title: string;
  slug?: string | null;
  category: 'campaign' | 'report' | 'field-guide' | 'policy-brief' | 'white-paper' | 'toolkit' | 'survey';
  status?: ('active' | 'past' | 'upcoming') | null;
  year?: number | null;
  endYear?: number | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  publishedAt?: string | null;
  authors?: string | null;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  accessType?: ('pdf' | 'url' | 'onsite') | null;
  pdf?: (string | null) | Media;
  externalUrl?: string | null;
  callToAction?: string | null;
  quotes?:
    | {
        quote: string;
        attribution?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * OCAB merch and products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  category?: ('apparel' | 'publication' | 'accessory' | 'other') | null;
  price?: string | null;
  outOfStock?: boolean | null;
  featured?: boolean | null;
  order?: number | null;
  description?: string | null;
  image?: (string | null) | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: string | Campaign;
      } | null)
    | ({
        relationTo: 'press-articles';
        value: string | PressArticle;
      } | null)
    | ({
        relationTo: 'team-members';
        value: string | TeamMember;
      } | null)
    | ({
        relationTo: 'books';
        value: string | Book;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  sections?:
    | T
    | {
        bannerSection?:
          | T
          | {
              label?: T;
              content?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              darkScrim?: T;
              padding?: T;
              id?: T;
              blockName?: T;
            };
        heroCarouselSection?:
          | T
          | {
              label?: T;
              slides?:
                | T
                | {
                    content?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    darkScrim?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fullWidthSection?:
          | T
          | {
              label?: T;
              content?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              darkScrim?: T;
              padding?: T;
              floatingItems?:
                | T
                | {
                    image?: T;
                    position?:
                      | T
                      | {
                          x?: T;
                          y?: T;
                          width?: T;
                          height?: T;
                        };
                    mobilePosition?:
                      | T
                      | {
                          x?: T;
                          y?: T;
                          width?: T;
                          height?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        twoColumnSection?:
          | T
          | {
              label?: T;
              wrapOnMobile?: T;
              ratio?: T;
              leftColumn?:
                | T
                | {
                    content?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    darkScrim?: T;
                  };
              rightColumn?:
                | T
                | {
                    content?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    darkScrim?: T;
                  };
              id?: T;
              blockName?: T;
            };
        threeColumnSection?:
          | T
          | {
              label?: T;
              wrapOnMobile?: T;
              column1?:
                | T
                | {
                    content?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    darkScrim?: T;
                  };
              column2?:
                | T
                | {
                    content?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    darkScrim?: T;
                  };
              column3?:
                | T
                | {
                    content?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    darkScrim?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactSection?:
          | T
          | {
              label?: T;
              title?: T;
              body?: T;
              showAddress?: T;
              showEmail?: T;
              showSocialIcons?: T;
              showForm?: T;
              backgroundColor?: T;
              backgroundImage?: T;
              darkScrim?: T;
              id?: T;
              blockName?: T;
            };
        contentGridSection?:
          | T
          | {
              label?: T;
              alignment?: T;
              verticalAlignment?: T;
              padding?: T;
              gap?: T;
              wrapOnMobile?: T;
              items?:
                | T
                | {
                    content?: T;
                    backgroundColor?: T;
                    backgroundImage?: T;
                    darkScrim?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        collectionListSection?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              dataSource?: T;
              layout?: T;
              columns?: T;
              limit?: T;
              sortField?: T;
              filterFeatured?: T;
              upcomingOnly?: T;
              viewAllLabel?: T;
              viewAllLinkType?: T;
              viewAllPage?: T;
              viewAllUrl?: T;
              emptyMessage?: T;
              pinnedItems?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              backgroundColor?: T;
              backgroundImage?: T;
              darkScrim?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  excerpt?: T;
  content?: T;
  publishedAt?: T;
  author?: T;
  authorName?: T;
  category?: T;
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedPosts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  actionNetworkId?: T;
  title?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  location?:
    | T
    | {
        venue?: T;
        address?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  browserUrl?: T;
  registrationUrl?: T;
  capacity?: T;
  totalAccepted?: T;
  slug?: T;
  status?: T;
  featured?: T;
  featuredImage?: T;
  longDescription?: T;
  eventType?: T;
  ticketed?: T;
  ticketUrl?: T;
  isFree?: T;
  price?: T;
  image?: T;
  order?: T;
  speakers?:
    | T
    | {
        name?: T;
        title?: T;
        bio?: T;
        photo?: T;
        id?: T;
      };
  sponsors?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        tier?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoKeywords?: T;
  backgroundColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  status?: T;
  year?: T;
  endYear?: T;
  featured?: T;
  order?: T;
  publishedAt?: T;
  authors?: T;
  summary?: T;
  content?: T;
  image?: T;
  accessType?: T;
  pdf?: T;
  externalUrl?: T;
  callToAction?: T;
  quotes?:
    | T
    | {
        quote?: T;
        attribution?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-articles_select".
 */
export interface PressArticlesSelect<T extends boolean = true> {
  title?: T;
  publication?: T;
  type?: T;
  excerpt?: T;
  url?: T;
  image?: T;
  featured?: T;
  order?: T;
  publishedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  pronouns?: T;
  type?: T;
  featured?: T;
  order?: T;
  bio?: T;
  photo?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  year?: T;
  isbn?: T;
  description?: T;
  cover?: T;
  url?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  price?: T;
  outOfStock?: T;
  featured?: T;
  order?: T;
  description?: T;
  image?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  navItems?:
    | {
        linkType?: ('page' | 'url') | null;
        page?: (string | null) | Page;
        /**
         * Must start with https://. Opens in a new tab.
         */
        url?: string | null;
        /**
         * What shows in the nav bar. If blank, uses the page title.
         */
        label?: string | null;
        subItems?:
          | {
              linkType?: ('page' | 'url') | null;
              page?: (string | null) | Page;
              url?: string | null;
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButtons?:
    | {
        label: string;
        style?: ('primary' | 'accent' | 'success' | 'neutral' | 'outline') | null;
        linkType?: ('page' | 'url') | null;
        page?: (string | null) | Page;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  style?: ('solid' | 'white') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (string | null) | Media;
  /**
   * Link to Zeffy, ActBlue, etc.
   */
  donateUrl?: string | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  socialMedia?: {
    instagram?: string | null;
    facebook?: string | null;
    twitter?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        linkType?: T;
        page?: T;
        url?: T;
        label?: T;
        subItems?:
          | T
          | {
              linkType?: T;
              page?: T;
              url?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        label?: T;
        style?: T;
        linkType?: T;
        page?: T;
        url?: T;
        id?: T;
      };
  style?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  donateUrl?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  socialMedia?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        twitter?: T;
        tiktok?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}